[package]
name = "jito-backrun-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.10"
futures-util = "0.3"
histogram = "0.7"
jito-protos = { path = "../jito_protos" }
jito-searcher-client = { path = "../searcher_client" }
log = "0.4"
rand = "0.8"
solana-client = "1.17"
solana-metrics = "1.17"
solana-sdk = "1.17"
solana-transaction-status = "1.17"
spl-memo = "4.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
tonic = "0.10"
